name: Melos action
description: Setup Melos for you GitHub workflow
author: Lukas Klingsbo
branding:
  icon: loader
  color: purple
inputs:
  melos-version:
    description: The Melos version to make available on the path
    required: false
  run-bootstrap:
    description: 'Whether bootstrap should run or not (default: true)'
    required: false
    default: 'true'
  publish-dry-run:
    description: 'Whether packages should be versioned and dry-run published (default: false)'
    required: false
    default: 'false'
  publish:
    description: 'Whether packages should be versioned and published to pub.dev (default: false)'
    required: false
    default: 'false'
  git-email:
    description: 'The email to use when committing changes'
    required: false
    default: 'contact@blue-fire.xyz'
  git-username:
    description: 'The name to use when committing changes'
    required: false
    default: 'Melos Action'
runs:
  using: composite
  steps:
    - name: Activate melos
      run: dart pub global activate melos ${{ inputs.melos-version }}
      shell: bash
    - name: Run melos bootstrap
      if: ${{ inputs.run-bootstrap == 'true' }}
      run: dart pub global run melos bootstrap
      shell: bash
    - name: Add melos to PATH
      run: command -v melos || echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH
      shell: bash
    - name: Set git config
      if: ${{ inputs.publish == 'true' || inputs.publish-dry-run == 'true' }}
      run: |
        git config --global user.email "${{ inputs.git-email }}"
        git config --global user.name "${{ inputs.git-username }}"
      shell: bash
    - name: Run melos version (dry run)
      if: ${{ inputs.publish-dry-run == 'true' }}
      run: melos version --yes --no-git-tag-version
      shell: bash
    - name: Run melos publish (dry run)
      if: ${{ inputs.publish-dry-run == 'true' }}
      run: melos publish -y --dry-run
      shell: bash
    - name: Run melos version
      if: ${{ inputs.publish == 'true' }}
      run: melos version --yes
      shell: bash
    - name: Run melos publish to pub.dev
      if: ${{ inputs.publish == 'true' }}
      run: melos publish -y --dry-run # Change to --no-dry-run once it is certain it works
      shell: bash
    - name: Create Pull Request with changes
      if: ${{ inputs.publish == 'true' }} # Change this to be done only if PR is requested
      uses: peter-evans/create-pull-request@v5
      with:
        title: 'chore(release): Publish packages'
        body: 'Updated CHANGELOG.md and pubspec.yaml for all packages after release to pub.dev'
        branch: release
